server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
# mybatis 相关配置属性
mybatis:
  # 定义 mapper 文件 位置
  mapper-locations: classpath:mybatis/*.xml