server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://106.75.187.191:9001/hdb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong&useSSL=false
    username: huhy01
    password: HUhaiyang1994.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000  #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接默认自动提交行为，默认为true
      max-lifetime: 1800000 #此属性控制池中连接最长生命周期，值为0表示无限生命周期，默认1800000 即30分钟
      connection-timeout: 30000 #数据库连接超时时间，默认是30秒， 即30000
      connection-test-query:  SELECT 1 FROM DUAL
beetlsql:
  sqlManagers: sqlManager1
  sqlManager1:
    ds: ds1
    nameConversion: org.beetl.sql.core.UnderlinedNameConversion
    dbStyle: org.beetl.sql.core.db.MySqlStyle
    basePackage: com.springboot.beetlsqldemo.mapper
    sqlRoot: /sql
    daoSuffix: Mapper